spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=25
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Security
security.jwt.secret=${JWT_SECRET}
security.jwt.access-token-expiry=${JWT_SECRET_EXPIRATION}
security.jwt.refresh-token-expiry=${JWT_REFRESH_EXPIRATION}

# API docs ? off in prod
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Misc
spring.jmx.enabled=false
loki.host=${LOKI_HOST:localhost}

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Verveguard - location anomaly enabled in prod
verveguard.location-anomaly.enabled=true

# ============================================================
# LOGGING ? prod profile
# ============================================================

# Root: only WARN and above
logging.level.root=WARN

# Your app: INFO so you see business-level events, errors, startup
logging.level.com.interswitch=INFO

# Spring framework internals ? silence unless something breaks
logging.level.org.springframework=WARN
logging.level.org.springframework.security=WARN
logging.level.org.springframework.web=WARN

# Hibernate ? never log SQL or parameters in prod
logging.level.org.hibernate=WARN
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

# HikariCP ? only pool errors
logging.level.com.zaxxer.hikari=WARN
logging.level.com.zaxxer.hikari.HikariConfig=WARN

# Flyway ? log migrations at INFO so you know what ran on startup
logging.level.org.flywaydb=INFO

# Silence noisy libraries
logging.level.io.netty=WARN
logging.level.reactor=WARN
verveguard.geo-ip.database-path=${GEOIP_DATABASE_PATH:/opt/geoip/GeoLite2-City.mmdb}