spring.application.name=wallet-app
spring.profiles.active=dev

server.port=${SERVER_PORT:8080}
spring.output.ansi.enabled=ALWAYS
logging.level.com.interswitch.walletapp=INFO
logging.level.com.zaxxer.hikari=WARN

spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.use_query_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory
spring.jpa.properties.hibernate.javax.cache.provider=com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider

spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=2

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=when-authorized
management.endpoint.health.show-components=when_authorized

management.metrics.tags.application=${spring.application.name}
management.observations.key-values.application=${spring.application.name}
management.prometheus.metrics.export.enabled=true

management.metrics.enable.http.server.requests=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# Email Configuration
app.email.enabled=${EMAIL_ENABLED:false}
app.email.host=${EMAIL_HOST:smtp.gmail.com}
app.email.port=${EMAIL_PORT:587}
app.email.username=${EMAIL_USERNAME:}
app.email.password=${GMAIL_APP_PASSWORD:}
app.email.from=${EMAIL_FROM`
