spring.datasource.url=jdbc:h2:mem:${DB_NAME:wallet_db};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=${DB_USERNAME:wallet_db_user}
spring.datasource.password=${DB_PASSWORD:wallet_db_pass}
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

# JWT fixed test values
security.jwt.secret=dGVzdC1zZWNyZXQta2V5LWZvci10ZXN0aW5nLW9ubHktMTIzNDU2Nzg=
security.jwt.access-token-expiry=900
security.jwt.refresh-token-expiry=604800

spring.jpa.show-sql=false

spring.flyway.locations=classpath:db/migration,classpath:db/testdata