spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

security.jwt.secret=${JWT_SECRET}
security.jwt.access-token-expiry=${JWT_SECRET_EXPIRATION}
security.jwt.refresh-token-expiry=${JWT_REFRESH_EXPIRATION}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/v3/api-docs
spring.flyway.locations=classpath:db/migration,classpath:db/testdata