spring.application.name=wallet-app
spring.profiles.active=dev

server.port=${SERVER_PORT:8080}
spring.output.ansi.enabled=ALWAYS
logging.level.interswitch.academy=INFO
logging.level.com.zaxxer.hikari=WARN

spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.use_query_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory
spring.jpa.properties.hibernate.javax.cache.provider=com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider

spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=2